// ReSharper disable ArrangeObjectCreationWhenTypeNotEvident
// THIS CODE WAS GENERATED BY A TOOL, PLEASE DO NOT TOUCH

namespace UwurandomSharp;

internal class CatgirlNonsense
{
    public static List<MarkovEntry> Table = new()
    {
        new(3,
            new()
            {
                new(0, 'a', 2), new(1, 'm', 3)
            }),
        new(4,
            new()
            {
                new(7, 'r', 3), new(6, 'e', 4)
            }),
        new(1, new() { new(8, 'y', 1) }),
        new(1, new() { new(9, 'w', 1) }),
        new(1, new() { new(9, 'w', 1) }),
        new(8,
            new()
            {
                new(21, 'm', 6), new(22, 'n', 7),
                new(23, 'p', 8)
            }),
        new(5,
            new()
            {
                new(4, 'o', 3), new(5, 'w', 5)
            }),
        new(30,
            new()
            {
                new(16, 'o', 15), new(12, 'a', 24),
                new(18, 'r', 28), new(19, 'w', 29),
                new(13, 'e', 30)
            }),
        new(1, new() { new(26, 'a', 1) }),
        new(38,
            new()
            {
                new(21, 'm', 22), new(24, 'r', 32),
                new(22, 'n', 36), new(25, 'w', 37),
                new(23, 'p', 38)
            }),
        new(1, new() { new(11, 'u', 1) }),
        new(1, new() { new(20, 'r', 1) }),
        new(1, new() { new(3, 'o', 1) }),
        new(1, new() { new(4, 'o', 1) }),
        new(2,
            new()
            {
                new(7, 'r', 1), new(6, 'e', 2)
            }),
        new(1, new() { new(8, 'y', 1) }),
        new(1, new() { new(9, 'w', 1) }),
        new(1, new() { new(10, 'p', 1) }),
        new(14,
            new()
            {
                new(18, 'r', 7), new(14, 'm', 10),
                new(16, 'o', 13), new(17, 'p', 14)
            }),
        new(1, new() { new(21, 'm', 1) }),
        new(1, new() { new(18, 'r', 1) }),
        new(30,
            new()
            {
                new(7, 'r', 17), new(6, 'e', 30)
            }),
        new(1, new() { new(8, 'y', 1) }),
        new(1, new() { new(11, 'u', 1) }),
        new(10,
            new()
            {
                new(14, 'm', 7), new(15, 'n', 10)
            }),
        new(4,
            new()
            {
                new(25, 'w', 3), new(21, 'm', 4)
            }),
        new(6,
            new()
            {
                new(0, 'a', 4), new(2, 'n', 5),
                new(1, 'm', 6)
            })
    };
}