// ReSharper disable ArrangeObjectCreationWhenTypeNotEvident
// THIS CODE WAS GENERATED BY A TOOL, PLEASE DO NOT TOUCH

namespace UwurandomSharp;

internal class Keysmash
{
    public static List<MarkovEntry> Table = new()
    {
        new(8,
            new()
            {
                new(1, 'a', 4), new(10, 'k', 5),
                new(3, 'd', 6), new(11, 'l', 7),
                new(7, 'h', 8)
            }),
        new(30,
            new()
            {
                new(7, 'h', 7), new(9, 'j', 13),
                new(5, 'f', 18), new(11, 'l', 21),
                new(16, 'u', 24), new(6, 'g', 26),
                new(3, 'd', 28), new(0, ';', 29),
                new(14, 'r', 30)
            }),
        new(3,
            new()
            {
                new(10, 'k', 1), new(1, 'a', 2),
                new(7, 'h', 3)
            }),
        new(17,
            new()
            {
                new(5, 'f', 7), new(7, 'h', 12),
                new(15, 's', 13), new(6, 'g', 14),
                new(10, 'k', 15), new(9, 'j', 16),
                new(2, 'b', 17)
            }),
        new(1, new() { new(6, 'g', 1) }),
        new(26,
            new()
            {
                new(6, 'g', 12), new(10, 'k', 16),
                new(9, 'j', 19), new(11, 'l', 21),
                new(7, 'h', 23), new(3, 'd', 25),
                new(1, 'a', 26)
            }),
        new(34,
            new()
            {
                new(1, 'a', 8), new(7, 'h', 14),
                new(0, ';', 18), new(9, 'j', 22),
                new(11, 'l', 25), new(2, 'b', 27),
                new(5, 'f', 29), new(3, 'd', 30),
                new(15, 's', 31), new(10, 'k', 32),
                new(16, 'u', 33), new(12, 'n', 34)
            }),
        new(31,
            new()
            {
                new(6, 'g', 7), new(9, 'j', 11),
                new(5, 'f', 14), new(10, 'k', 17),
                new(1, 'a', 20), new(3, 'd', 23),
                new(8, 'i', 25), new(14, 'r', 27),
                new(0, ';', 28), new(12, 'n', 29),
                new(7, 'h', 30), new(16, 'u', 31)
            }),
        new(1, new() { new(16, 'u', 1) }),
        new(22,
            new()
            {
                new(7, 'h', 5), new(3, 'd', 9),
                new(10, 'k', 12), new(5, 'f', 15),
                new(1, 'a', 17), new(14, 'r', 18),
                new(4, 'e', 19), new(13, 'o', 20),
                new(11, 'l', 21), new(6, 'g', 22)
            }),
        new(20,
            new()
            {
                new(1, 'a', 6), new(5, 'f', 10),
                new(6, 'g', 13), new(9, 'j', 16),
                new(15, 's', 17), new(3, 'd', 18),
                new(11, 'l', 19), new(7, 'h', 20)
            }),
        new(11,
            new()
            {
                new(10, 'k', 4), new(0, ';', 6),
                new(15, 's', 7), new(6, 'g', 8),
                new(5, 'f', 9), new(3, 'd', 10),
                new(1, 'a', 11)
            }),
        new(2,
            new()
            {
                new(6, 'g', 1), new(7, 'h', 2)
            }),
        new(1, new() { new(6, 'g', 1) }),
        new(7,
            new()
            {
                new(6, 'g', 4), new(1, 'a', 6),
                new(7, 'h', 7)
            }),
        new(2,
            new()
            {
                new(3, 'd', 1), new(10, 'k', 2)
            }),
        new(7,
            new()
            {
                new(14, 'r', 3), new(1, 'a', 4),
                new(5, 'f', 5), new(9, 'j', 6),
                new(4, 'e', 7)
            })
    };
}