// ReSharper disable ArrangeObjectCreationWhenTypeNotEvident
// THIS CODE WAS GENERATED BY A TOOL, PLEASE DO NOT TOUCH

namespace UwurandomSharp;

internal class TheScrunkly
{
    public static List<MarkovEntry> Table = new()
    {
        new(1067,
            new()
            {
                new(34, 'n', 500),
                new(37, 'w', 867),
                new(31, 'd', 1067)
            }),
        new(1, new() { new(43, 'o', 1) }),
        new(147,
            new()
            {
                new(46, 'u', 60), new(45, 'r', 107),
                new(44, 'a', 147)
            }),
        new(1, new() { new(51, 'o', 1) }),
        new(1, new() { new(61, 'l', 1) }),
        new(1, new() { new(64, 'a', 1) }),
        new(364,
            new()
            {
                new(77, 't', 200),
                new(70, 'c', 300),
                new(68, ',', 325),
                new(67, '!', 349),
                new(69, '.', 364)
            }),
        new(3,
            new()
            {
                new(81, 'i', 2), new(79, 'd', 3)
            }),
        new(5,
            new()
            {
                new(88, 'i', 4), new(89, 'o', 5)
            }),
        new(2,
            new()
            {
                new(95, 'i', 1), new(94, 'e', 2)
            }),
        new(81,
            new()
            {
                new(107, 'o', 50), new(98, ' ', 81)
            }),
        new(1271,
            new()
            {
                new(135, 'c', 535),
                new(140, 'p', 835),
                new(139, 'o', 1100),
                new(138, 'm', 1200),
                new(136, 'h', 1271)
            }),
        new(478,
            new()
            {
                new(149, 'h', 262),
                new(152, 'o', 362),
                new(150, 'i', 453),
                new(147, 'a', 478)
            }),
        new(19,
            new()
            {
                new(165, 'h', 11),
                new(166, 'i', 19)
            }),
        new(1, new() { new(173, 'a', 1) }),
        new(849,
            new()
            {
                new(12, 't', 190), new(0, 'a', 326),
                new(11, 's', 454), new(8, 'l', 572),
                new(2, 'c', 646), new(14, 'y', 684),
                new(5, 'h', 722), new(13, 'w', 757),
                new(1, 'b', 790), new(10, 'n', 821),
                new(6, 'i', 849)
            }),
        new(60,
            new()
            {
                new(15, ' ', 31), new(16, '!', 60)
            }),
        new(1585,
            new()
            {
                new(17, ',', 777),
                new(26, 't', 965),
                new(18, 'a', 1098),
                new(25, 's', 1227),
                new(23, 'l', 1322),
                new(20, 'c', 1387),
                new(24, 'n', 1425),
                new(28, 'y', 1462),
                new(22, 'i', 1498),
                new(19, 'b', 1531),
                new(21, 'h', 1560),
                new(27, 'w', 1585)
            }),
        new(1, new() { new(37, 'w', 1) }),
        new(1, new() { new(43, 'o', 1) }),
        new(1, new() { new(45, 'r', 1) }),
        new(1, new() { new(64, 'a', 1) }),
        new(18,
            new()
            {
                new(67, '!', 7), new(68, ',', 13),
                new(69, '.', 18)
            }),
        new(95,
            new()
            {
                new(89, 'o', 59), new(88, 'i', 95)
            }),
        new(1, new() { new(98, ' ', 1) }),
        new(129,
            new()
            {
                new(135, 'c', 65),
                new(139, 'o', 100),
                new(136, 'h', 129)
            }),
        new(47,
            new()
            {
                new(149, 'h', 38),
                new(150, 'i', 47)
            }),
        new(1, new() { new(165, 'h', 1) }),
        new(1, new() { new(173, 'a', 1) }),
        new(843,
            new()
            {
                new(12, 't', 222),
                new(11, 's', 365), new(0, 'a', 496),
                new(8, 'l', 583), new(2, 'c', 644),
                new(13, 'w', 684), new(6, 'i', 720),
                new(1, 'b', 754), new(5, 'h', 787),
                new(10, 'n', 818),
                new(14, 'y', 843)
            }),
        new(1271,
            new()
            {
                new(29, ' ', 638),
                new(30, '.', 1271)
            }),
        new(1, new() { new(51, 'o', 1) }),
        new(1, new() { new(87, 'e', 1) }),
        new(1, new() { new(97, 't', 1) }),
        new(6,
            new()
            {
                new(103, 'd', 5), new(98, ' ', 6)
            }),
        new(2,
            new()
            {
                new(122, ' ', 1), new(123, 'p', 2)
            }),
        new(1, new() { new(143, ' ', 1) }),
        new(500,
            new()
            {
                new(168, 'w', 300),
                new(161, ' ', 400),
                new(162, '!', 443),
                new(164, '.', 473),
                new(163, ',', 500)
            }),
        new(50,
            new()
            {
                new(170, '!', 17),
                new(172, '.', 34),
                new(171, ',', 50)
            }),
        new(33,
            new()
            {
                new(16, '!', 29), new(15, ' ', 33)
            }),
        new(1, new() { new(17, ',', 1) }),
        new(9,
            new()
            {
                new(30, '.', 7), new(29, ' ', 9)
            }),
        new(3,
            new()
            {
                new(89, 'o', 2), new(87, 'e', 3)
            }),
        new(1, new() { new(113, 'i', 1) }),
        new(3,
            new()
            {
                new(34, 'n', 1), new(33, 'm', 2),
                new(36, 't', 3)
            }),
        new(9,
            new()
            {
                new(131, 'u', 5), new(128, 'i', 9)
            }),
        new(1, new() { new(159, 't', 1) }),
        new(5,
            new()
            {
                new(2, 'c', 2), new(3, 'd', 3),
                new(6, 'i', 4), new(11, 's', 5)
            }),
        new(100,
            new()
            {
                new(41, '.', 36), new(39, '!', 69),
                new(40, ',', 100)
            }),
        new(1, new() { new(50, 'l', 1) }),
        new(1, new() { new(87, 'e', 1) }),
        new(5,
            new()
            {
                new(118, 'r', 2), new(117, 'o', 4),
                new(120, 'u', 5)
            }),
        new(25,
            new()
            {
                new(12, 't', 6), new(11, 's', 10),
                new(8, 'l', 13), new(2, 'c', 16),
                new(0, 'a', 18), new(13, 'w', 20),
                new(1, 'b', 22), new(7, 'k', 24),
                new(9, 'm', 25)
            }),
        new(208,
            new()
            {
                new(16, '!', 157),
                new(15, ' ', 208)
            }),
        new(1, new() { new(17, ',', 1) }),
        new(101,
            new()
            {
                new(30, '.', 80), new(29, ' ', 101)
            }),
        new(1, new() { new(92, ' ', 1) }),
        new(600,
            new()
            {
                new(108, 'p', 400),
                new(98, ' ', 500),
                new(101, '.', 536),
                new(99, '!', 569),
                new(100, ',', 600)
            }),
        new(1, new() { new(121, 'w', 1) }),
        new(1, new() { new(141, 't', 1) }),
        new(1, new() { new(0, 'a', 1) }),
        new(1, new() { new(90, 'u', 1) }),
        new(200,
            new()
            {
                new(53, '!', 74), new(54, ',', 139),
                new(55, '.', 200)
            }),
        new(1, new() { new(87, 'e', 1) }),
        new(1, new() { new(35, 'p', 1) }),
        new(1600,
            new()
            {
                new(52, ' ', 1200),
                new(57, 'n', 1400),
                new(56, 'm', 1500),
                new(53, '!', 1537),
                new(54, ',', 1569),
                new(55, '.', 1600)
            }),
        new(1, new() { new(130, 'o', 1) }),
        new(38,
            new()
            {
                new(16, '!', 25), new(15, ' ', 38)
            }),
        new(1, new() { new(17, ',', 1) }),
        new(25,
            new()
            {
                new(30, '.', 17), new(29, ' ', 25)
            }),
        new(1, new() { new(44, 'a', 1) }),
        new(1, new() { new(49, 'd', 1) }),
        new(500,
            new()
            {
                new(57, 'n', 400),
                new(55, '.', 443),
                new(54, ',', 479),
                new(53, '!', 500)
            }),
        new(1, new() { new(80, 'e', 1) }),
        new(2,
            new()
            {
                new(93, 'b', 1), new(97, 't', 2)
            }),
        new(7,
            new()
            {
                new(106, 'k', 6), new(105, 'g', 7)
            }),
        new(1, new() { new(127, 'y', 1) }),
        new(1000,
            new()
            {
                new(154, 't', 300),
                new(143, ' ', 600),
                new(146, '.', 706),
                new(155, 'y', 806),
                new(145, ',', 905),
                new(144, '!', 1000)
            }),
        new(1, new() { new(160, 'e', 1) }),
        new(1, new() { new(48, 'b', 1) }),
        new(1, new() { new(52, ' ', 1) }),
        new(4,
            new()
            {
                new(77, 't', 3), new(74, 'm', 4)
            }),
        new(7,
            new()
            {
                new(91, 'y', 6), new(87, 'e', 7)
            }),
        new(100,
            new()
            {
                new(112, '.', 39),
                new(110, '!', 72),
                new(111, ',', 100)
            }),
        new(1, new() { new(158, 's', 1) }),
        new(1, new() { new(169, ' ', 1) }),
        new(1, new() { new(11, 's', 1) }),
        new(600,
            new()
            {
                new(52, ' ', 550),
                new(53, '!', 569),
                new(55, '.', 586),
                new(54, ',', 600)
            }),
        new(6,
            new()
            {
                new(77, 't', 3), new(73, 'k', 4),
                new(78, 'v', 5), new(74, 'm', 6)
            }),
        new(200,
            new()
            {
                new(117, 'o', 100),
                new(109, ' ', 150),
                new(110, '!', 169),
                new(111, ',', 187),
                new(112, '.', 200)
            }),
        new(1, new() { new(157, 'n', 1) }),
        new(500,
            new()
            {
                new(169, ' ', 300),
                new(170, '!', 373),
                new(172, '.', 439),
                new(171, ',', 500)
            }),
        new(1, new() { new(12, 't', 1) }),
        new(1, new() { new(42, 'l', 1) }),
        new(1, new() { new(58, 'o', 1) }),
        new(1, new() { new(76, 'p', 1) }),
        new(1, new() { new(115, 'l', 1) }),
        new(300,
            new()
            {
                new(151, 'l', 100),
                new(155, 'y', 200),
                new(146, '.', 238),
                new(145, ',', 273),
                new(144, '!', 300)
            }),
        new(3,
            new()
            {
                new(12, 't', 2), new(4, 'f', 3)
            }),
        new(33,
            new()
            {
                new(16, '!', 26), new(15, ' ', 33)
            }),
        new(1, new() { new(17, ',', 1) }),
        new(36,
            new()
            {
                new(30, '.', 25), new(29, ' ', 36)
            }),
        new(1, new() { new(32, 'l', 1) }),
        new(1, new() { new(47, ' ', 1) }),
        new(1, new() { new(60, ' ', 1) }),
        new(2,
            new()
            {
                new(62, 'e', 1), new(63, 'l', 2)
            }),
        new(11,
            new()
            {
                new(82, 'l', 7), new(85, 'y', 9),
                new(84, 'u', 10), new(83, 'o', 11)
            }),
        new(1, new() { new(121, 'w', 1) }),
        new(1, new() { new(125, 's', 1) }),
        new(5,
            new()
            {
                new(0, 'a', 1), new(6, 'i', 2),
                new(8, 'l', 3), new(1, 'b', 4),
                new(9, 'm', 5)
            }),
        new(136,
            new()
            {
                new(16, '!', 105),
                new(15, ' ', 136)
            }),
        new(1, new() { new(17, ',', 1) }),
        new(141,
            new()
            {
                new(30, '.', 104),
                new(29, ' ', 141)
            }),
        new(1, new() { new(75, 'n', 1) }),
        new(1, new() { new(81, 'i', 1) }),
        new(1, new() { new(86, ' ', 1) }),
        new(1, new() { new(106, 'k', 1) }),
        new(900,
            new()
            {
                new(119, 't', 300),
                new(114, 'k', 500),
                new(117, 'o', 600),
                new(109, ' ', 700),
                new(112, '.', 776),
                new(110, '!', 841),
                new(111, ',', 900)
            }),
        new(1, new() { new(129, 'n', 1) }),
        new(1, new() { new(153, 's', 1) }),
        new(1, new() { new(156, 'b', 1) }),
        new(3,
            new()
            {
                new(161, ' ', 2), new(167, 'm', 3)
            }),
        new(1, new() { new(10, 'n', 1) }),
        new(1, new() { new(127, 'y', 1) }),
        new(1, new() { new(130, 'o', 1) }),
        new(1, new() { new(142, 'y', 1) }),
        new(1, new() { new(157, 'n', 1) }),
        new(200,
            new()
            {
                new(169, ' ', 100),
                new(170, '!', 141),
                new(171, ',', 177),
                new(172, '.', 200)
            }),
        new(2,
            new()
            {
                new(75, 'n', 1), new(74, 'm', 2)
            }),
        new(1, new() { new(102, 'a', 1) }),
        new(2,
            new()
            {
                new(116, 'n', 1), new(113, 'i', 2)
            }),
        new(1, new() { new(157, 'n', 1) }),
        new(11,
            new()
            {
                new(16, '!', 8), new(15, ' ', 11)
            }),
        new(1, new() { new(17, ',', 1) }),
        new(17,
            new()
            {
                new(30, '.', 13), new(29, ' ', 17)
            }),
        new(1, new() { new(45, 'r', 1) }),
        new(1, new() { new(66, 'r', 1) }),
        new(3,
            new()
            {
                new(77, 't', 2), new(72, 'e', 3)
            }),
        new(1, new() { new(96, 'o', 1) }),
        new(3,
            new()
            {
                new(109, ' ', 2), new(117, 'o', 3)
            }),
        new(3,
            new()
            {
                new(126, 'u', 2), new(124, 'r', 3)
            }),
        new(1, new() { new(143, ' ', 1) }),
        new(400,
            new()
            {
                new(169, ' ', 300),
                new(172, '.', 341),
                new(171, ',', 376),
                new(170, '!', 400)
            }),
        new(6,
            new()
            {
                new(12, 't', 2), new(0, 'a', 4),
                new(2, 'c', 5), new(11, 's', 6)
            }),
        new(122,
            new()
            {
                new(16, '!', 85), new(15, ' ', 122)
            }),
        new(1, new() { new(17, ',', 1) }),
        new(144,
            new()
            {
                new(30, '.', 101),
                new(29, ' ', 144)
            }),
        new(1, new() { new(35, 'p', 1) }),
        new(300,
            new()
            {
                new(59, 's', 200),
                new(53, '!', 238),
                new(55, '.', 271),
                new(54, ',', 300)
            }),
        new(1, new() { new(65, 'e', 1) }),
        new(1, new() { new(72, 'e', 1) }),
        new(1, new() { new(87, 'e', 1) }),
        new(4,
            new()
            {
                new(117, 'o', 3), new(109, ' ', 4)
            }),
        new(1, new() { new(137, 'i', 1) }),
        new(1, new() { new(151, 'l', 1) }),
        new(200,
            new()
            {
                new(169, ' ', 100),
                new(171, ',', 138),
                new(170, '!', 169),
                new(172, '.', 200)
            }),
        new(1, new() { new(42, 'l', 1) }),
        new(8,
            new()
            {
                new(106, 'k', 4), new(105, 'g', 7),
                new(104, 'f', 8)
            }),
        new(100,
            new()
            {
                new(134, '.', 34),
                new(132, '!', 67),
                new(133, ',', 100)
            }),
        new(1, new() { new(148, 'e', 1) }),
        new(1, new() { new(52, ' ', 1) }),
        new(6,
            new()
            {
                new(12, 't', 2), new(8, 'l', 3),
                new(11, 's', 4), new(13, 'w', 5),
                new(6, 'i', 6)
            }),
        new(43,
            new()
            {
                new(16, '!', 24), new(15, ' ', 43)
            }),
        new(1, new() { new(17, ',', 1) }),
        new(5,
            new()
            {
                new(30, '.', 4), new(29, ' ', 5)
            }),
        new(1, new() { new(65, 'e', 1) }),
        new(1, new() { new(71, 'd', 1) }),
        new(1, new() { new(94, 'e', 1) }),
        new(5,
            new()
            {
                new(161, ' ', 3), new(168, 'w', 5)
            }),
        new(10,
            new()
            {
                new(12, 't', 2), new(11, 's', 4),
                new(3, 'd', 6), new(0, 'a', 8),
                new(7, 'k', 9), new(13, 'w', 10)
            }),
        new(7,
            new()
            {
                new(16, '!', 5), new(15, ' ', 7)
            }),
        new(1, new() { new(17, ',', 1) }),
        new(65,
            new()
            {
                new(30, '.', 51), new(29, ' ', 65)
            }),
        new(1, new() { new(38, 'y', 1) })
    };
}